/**
 * Slug helpers — mirrors the Phase 1 dev adapter (src/server/dev-store/ids.ts)
 * so URLs generated by the backend stay identical in style.
 */

export function slugify(input: string): string {
  return input
    .toLowerCase()
    .trim()
    .replace(/['’]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 120);
}

/** Ensures the slug is unique, appending -2, -3… */
export function uniqueSlug(base: string, isTaken: (candidate: string) => Promise<boolean>): Promise<string> {
  const root = slugify(base) || "item";
  return (async () => {
    if (!(await isTaken(root))) return root;
    let n = 2;
    while (await isTaken(`${root}-${n}`)) n += 1;
    return `${root}-${n}`;
  })();
}

/** Auto SKU: MIC-0007 style counter based on the current product count. */
export function skuFromCount(count: number): string {
  return `MIC-${String(count + 1).padStart(4, "0")}`;
}
